import Navbar from "../../../../components/admin/Navbar/Navbar";
import styles from "../../../../pages/admin/posts/posts.module.scss";
import http from "../../../../http-config";
import Head from "next/head";

function Index({ post }) {
  return (
    <div>
      <Head>
        <title>Admin Post Detail - {post.data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {post && (
        <div className={styles.postsContainer}>
          <div className={styles.posts}>
            <div className={styles.post} key={post._id}>
              <h3>{post.data.title}</h3>
              <p>{post.data.description}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(`${http}/api/admin/posts/${context.query.id}`);
  const post = await res.json();

  return {
    props: { post },
  };
}

export default Index;
